# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PSO3DViews.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PSO3DViews(object):
    def setupUi(self, PSO3DViews):
        PSO3DViews.setObjectName("PSO3DViews")
        PSO3DViews.resize(1443, 928)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PSO3DViews.sizePolicy().hasHeightForWidth())
        PSO3DViews.setSizePolicy(sizePolicy)
        PSO3DViews.setStatusTip("")
        PSO3DViews.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        PSO3DViews.setTabShape(QtWidgets.QTabWidget.Rounded)
        PSO3DViews.setDockNestingEnabled(True)
        PSO3DViews.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PSO3DViews)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_16 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.widget_16)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.spinBox_times = QtWidgets.QSpinBox(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_times.sizePolicy().hasHeightForWidth())
        self.spinBox_times.setSizePolicy(sizePolicy)
        self.spinBox_times.setMaximum(1000)
        self.spinBox_times.setProperty("value", 100)
        self.spinBox_times.setObjectName("spinBox_times")
        self.horizontalLayout_14.addWidget(self.spinBox_times)
        self.verticalLayout.addWidget(self.widget_16)
        self.widget_15 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.widget_15)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.spinBox_pop_size = QtWidgets.QSpinBox(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_pop_size.sizePolicy().hasHeightForWidth())
        self.spinBox_pop_size.setSizePolicy(sizePolicy)
        self.spinBox_pop_size.setMaximum(1000)
        self.spinBox_pop_size.setProperty("value", 100)
        self.spinBox_pop_size.setObjectName("spinBox_pop_size")
        self.horizontalLayout_13.addWidget(self.spinBox_pop_size)
        self.verticalLayout.addWidget(self.widget_15)
        self.widget_2 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBox_omega = QtWidgets.QDoubleSpinBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_omega.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_omega.setSizePolicy(sizePolicy)
        self.doubleSpinBox_omega.setProperty("value", 0.9)
        self.doubleSpinBox_omega.setObjectName("doubleSpinBox_omega")
        self.horizontalLayout.addWidget(self.doubleSpinBox_omega)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.doubleSpinBox_c1 = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_c1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_c1.setSizePolicy(sizePolicy)
        self.doubleSpinBox_c1.setProperty("value", 2.0)
        self.doubleSpinBox_c1.setObjectName("doubleSpinBox_c1")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_c1)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_r1_min = QtWidgets.QDoubleSpinBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_r1_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_r1_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_r1_min.setObjectName("doubleSpinBox_r1_min")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_r1_min)
        self.line = QtWidgets.QFrame(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.doubleSpinBox_r1_max = QtWidgets.QDoubleSpinBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_r1_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_r1_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_r1_max.setProperty("value", 1.0)
        self.doubleSpinBox_r1_max.setObjectName("doubleSpinBox_r1_max")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_r1_max)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.doubleSpinBox_c2 = QtWidgets.QDoubleSpinBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_c2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_c2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_c2.setProperty("value", 2.0)
        self.doubleSpinBox_c2.setObjectName("doubleSpinBox_c2")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_c2)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.doubleSpinBox_r2_min = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_r2_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_r2_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_r2_min.setObjectName("doubleSpinBox_r2_min")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_r2_min)
        self.line_2 = QtWidgets.QFrame(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.doubleSpinBox_r2_max = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_r2_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_r2_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_r2_max.setProperty("value", 1.0)
        self.doubleSpinBox_r2_max.setObjectName("doubleSpinBox_r2_max")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_r2_max)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_fitness_function = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_fitness_function.setObjectName("lineEdit_fitness_function")
        self.horizontalLayout_6.addWidget(self.lineEdit_fitness_function)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_12 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.widget_12)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.doubleSpinBox_x1_min = QtWidgets.QDoubleSpinBox(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x1_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x1_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x1_min.setObjectName("doubleSpinBox_x1_min")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_x1_min)
        self.line_3 = QtWidgets.QFrame(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.doubleSpinBox_x1_max = QtWidgets.QDoubleSpinBox(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x1_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x1_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x1_max.setProperty("value", 15.0)
        self.doubleSpinBox_x1_max.setObjectName("doubleSpinBox_x1_max")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_x1_max)
        self.verticalLayout.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.widget_13)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.doubleSpinBox_x2_min = QtWidgets.QDoubleSpinBox(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x2_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x2_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x2_min.setObjectName("doubleSpinBox_x2_min")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_x2_min)
        self.line_4 = QtWidgets.QFrame(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_10.addWidget(self.line_4)
        self.doubleSpinBox_x2_max = QtWidgets.QDoubleSpinBox(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x2_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x2_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x2_max.setProperty("value", 15.0)
        self.doubleSpinBox_x2_max.setObjectName("doubleSpinBox_x2_max")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_x2_max)
        self.verticalLayout.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.widget_14)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.doubleSpinBox_x3_min = QtWidgets.QDoubleSpinBox(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x3_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x3_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x3_min.setObjectName("doubleSpinBox_x3_min")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_x3_min)
        self.line_5 = QtWidgets.QFrame(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_11.addWidget(self.line_5)
        self.doubleSpinBox_x3_max = QtWidgets.QDoubleSpinBox(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x3_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x3_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x3_max.setProperty("value", 15.0)
        self.doubleSpinBox_x3_max.setObjectName("doubleSpinBox_x3_max")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_x3_max)
        self.verticalLayout.addWidget(self.widget_14)
        self.widget_17 = QtWidgets.QWidget(self.widget_8)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.pushButton_start_calculate = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_start_calculate.setObjectName("pushButton_start_calculate")
        self.horizontalLayout_12.addWidget(self.pushButton_start_calculate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_17)
        self.horizontalLayout_15.addWidget(self.widget_8)
        self.widget_11 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_10)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.widget_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.comboBox_result_history = QtWidgets.QComboBox(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_result_history.sizePolicy().hasHeightForWidth())
        self.comboBox_result_history.setSizePolicy(sizePolicy)
        self.comboBox_result_history.setObjectName("comboBox_result_history")
        self.horizontalLayout_7.addWidget(self.comboBox_result_history)
        self.label_7 = QtWidgets.QLabel(self.widget_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.doubleSpinBox_play_rate = QtWidgets.QDoubleSpinBox(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_play_rate.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_play_rate.setSizePolicy(sizePolicy)
        self.doubleSpinBox_play_rate.setProperty("value", 2.0)
        self.doubleSpinBox_play_rate.setObjectName("doubleSpinBox_play_rate")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_play_rate)
        self.pushButton_start_play = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_start_play.setObjectName("pushButton_start_play")
        self.horizontalLayout_7.addWidget(self.pushButton_start_play)
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.gridLayout_3.addWidget(self.widget_10, 1, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.widget_11)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        PSO3DViews.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PSO3DViews)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1443, 21))
        self.menubar.setObjectName("menubar")
        PSO3DViews.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PSO3DViews)
        self.statusbar.setObjectName("statusbar")
        PSO3DViews.setStatusBar(self.statusbar)

        self.retranslateUi(PSO3DViews)
        QtCore.QMetaObject.connectSlotsByName(PSO3DViews)

    def retranslateUi(self, PSO3DViews):
        _translate = QtCore.QCoreApplication.translate
        PSO3DViews.setWindowTitle(_translate("PSO3DViews", "UI for Particle Swarm Optimization Algorithm"))
        self.label_10.setText(_translate("PSO3DViews", "迭代次数:"))
        self.label_9.setText(_translate("PSO3DViews", "种群数量:"))
        self.label.setText(_translate("PSO3DViews", "惯性参数w:"))
        self.label_2.setText(_translate("PSO3DViews", "c1:"))
        self.label_3.setText(_translate("PSO3DViews", "r1:"))
        self.label_4.setText(_translate("PSO3DViews", "c2:"))
        self.label_5.setText(_translate("PSO3DViews", "r2:"))
        self.label_6.setText(_translate("PSO3DViews", "适应函数："))
        self.lineEdit_fitness_function.setPlaceholderText(_translate("PSO3DViews", "(2 * x1 ** 2 - 3 * x2 ** 2 - 4 * x1 + 5 * x2 + x3) * 100"))
        self.label_8.setText(_translate("PSO3DViews", "x1"))
        self.label_11.setText(_translate("PSO3DViews", "x2"))
        self.label_12.setText(_translate("PSO3DViews", "x3"))
        self.pushButton_start_calculate.setText(_translate("PSO3DViews", "开始计算"))
        self.groupBox.setTitle(_translate("PSO3DViews", "PSO可视化全区域"))
        self.label_13.setText(_translate("PSO3DViews", "历史结果："))
        self.label_7.setText(_translate("PSO3DViews", "播放速度（每秒刷新次数）："))
        self.pushButton_start_play.setText(_translate("PSO3DViews", "播放动画"))
